@echo off
cd /d "C:\Users\Asus\Desktop\files (7)\skillchain-backend"
echo Removing test files...
rmdir /s /q tests 2>nul
echo Removing demo folder...
rmdir /s /q demo 2>nul
echo Removing migrations folder...
rmdir /s /q migrations 2>nul
echo Removing backup file...
del /f /q package-lock.json.bak 2>nul
echo Cleanup complete!
pause
